services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - /path/to/cloudflared/:/etc/cloudflared 
      # HOST/PC/PATH:DOCKER/CONTAINER/PATH
      # ~/.cloudflared:/etc/cloudflared
      # /etc/cloudflared:/etc/cloudflared
    networks:
      - seafile-net
    restart: unless-stopped

networks:
  seafile-net:
    external: true
