services:

  caddy:
    image: ${SEAFILE_CADDY_IMAGE:-lucaslorentz/caddy-docker-proxy:2.9-alpine}
    restart: unless-stopped
    container_name: seafile-caddy
    ports:
      - 80:80
      # - 443:443  # this has been disabled to prevent HTTPS redirect, cloudflared handles it
    environment:
      - CADDY_INGRESS_NETWORKS=seafile-net
      - CADDY_DOCKER_PROXY_UPSTREAM=http://seafile:80 # Force HTTP upstream
      - CADDY_DOCKER_PROXY_HEADER_X-Forwarded-Proto=https 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SEAFILE_CADDY_VOLUME:-/opt/seafile-caddy}:/data/caddy
    networks:
      - seafile-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:2019/metrics || exit 1"]
      start_period: 20s
      interval: 20s
      timeout: 5s
      retries: 3

networks:
  seafile-net:
    name: seafile-net
