services:
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ${CLOUDFLARED_CONFIG_FILE_PATH}:/etc/cloudflared
    networks:
      - seafile-net
    restart: unless-stopped

networks:
  seafile-net:
    external: true
